
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: MoneeDB
      POSTGRES_USER: quimet
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: